
[versions]
android = "4.1.3"
changelog = "1.1.2"
detekt = "1.16.0"
dokka = "1.4.32"
gradlePublish = "0.13.0"
kotlin = "1.5.0"
kotlinBinaryValidator = "0.5.0"
mkdocs = "2.1.1"
nexusPublish = "1.1.0"
reckon = "0.13.0"
spotless = "5.12.4"
versions = "0.38.0"

[libraries]
android-toolsBuild-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "android" }
diffplug-spotless-spotlessPluginGradle = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }
github-benManes-gradleVersionsPlugin = { group = "com.github.ben-manes", name = "gradle-versions-plugin", version.ref = "versions" }
gradle-publish-pluginPublishPlugin = { group = "com.gradle.publish", name = "plugin-publish-plugin", version.ref = "gradlePublish" }
github-gradleNexus-publishPlugin = { group = "io.github.gradle-nexus", name = "publish-plugin", version.ref = "nexusPublish" }
gitlab-arturboschDetekt-detektGradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
ajoberstar-reckon-reckonGradle = { group = "org.ajoberstar.reckon", name = "reckon-gradle", version.ref = "reckon" }
jetbrains-dokka-dokkaGradlePlugin = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version.ref = "dokka" }
jetbrains-intellijPlugins-gradleChangelogPlugin = { group = "org.jetbrains.intellij.plugins", name = "gradle-changelog-plugin", version.ref = "changelog" }
jetbrains-kotlin-kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
jetbrains-kotlinx-binaryCompatibilityValidator = { group = "org.jetbrains.kotlinx", name = "binary-compatibility-validator", version.ref = "kotlinBinaryValidator" }
vyarus-gradleMkdocsPlugin = { group = "ru.vyarus", name = "gradle-mkdocs-plugin", version.ref = "mkdocs" }
