site_name: gradle-plugins

# Meta tags (placed in header)
site_description:
#site_author: Your Name
#site_url: https://you.github.io/gradle-plugins

# Repository (add link to repository on each page)
#repo_name: gradle-plugins
#repo_url: http://github.com/you/gradle-plugins
#edit_uri: edit/master/D:\Repos\Kotlin\gradle-plugins/.docs/src/doc/docs/

copyright: 'Copyright &copy; 2021 Javier Segovia Córdoba'

theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'white'
    accent: 'white'
  font:
    text: 'Fira Sans'
    code: 'JetBrains Mono'

nav:
  - Overview: index.md

plugins:
  - search

#  social:
#    - icon: fontawesome/brands/github
#      link: https://github.com/you
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/you


# Google Analytics
#google_analytics:
#  - 'UA-111111111-1'
#  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - def_list
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences



extra_css:
  - _extras/all.css
